In [1]:
import numpy as np
uniform=np.random.rand(3,3)
print("Uniform Distridution:\n",uniform)

Uniform Distridution:
 [[0.85073368 0.01274021 0.93085623]
 [0.07556603 0.41990163 0.38626909]
 [0.97820348 0.29915441 0.49331237]]


In [2]:
#searching in array where----returns the index value 
a=np.array([1,2,3,4,5])
np.where(a>3)

(array([3, 4], dtype=int64),)

In [3]:
np.where(a>4)

(array([4], dtype=int64),)

In [4]:
np.where(a<2)

(array([0], dtype=int64),)

In [5]:
np.argmax(a)

4

In [6]:
np.argmin(a)

0

In [7]:
#searchsorted
sorted_arr=np.array([1,3,5,7])
np.searchsorted(sorted_arr,6)

3

In [8]:
np.searchsorted(sorted_arr,4)

2

In [ ]:
#extract --- retuns the value 

In [9]:
np.extract(a>3,a)

array([4, 5])

In [10]:
#transpose
matrix=([[1,2,3],[4,5,6]])
matrix

[[1, 2, 3], [4, 5, 6]]

In [20]:
np.transpose(matrix)

array([[1, 4],
       [2, 5],
       [3, 6]])

In [21]:
#mean
print("Mean Value",np.mean(a))

Mean Value 3.0


In [22]:
#splitting arrays
#--equal parts split
aa=np.array([1,2,3,4,5,6])
np.split(aa,2)

[array([1, 2, 3]), array([4, 5, 6])]

In [23]:
np.split(aa,3)

[array([1, 2]), array([3, 4]), array([5, 6])]

In [24]:
#--split at specific positions

In [25]:
np.split(aa,[2,4])

[array([1, 2]), array([3, 4]), array([5, 6])]

In [27]:
#matrix
mat=np.array([[1,2,3],
              [4,5,6]])
np.split(mat, 3,axis=1)

[array([[1],
        [4]]),
 array([[2],
        [5]]),
 array([[3],
        [6]])]

In [28]:
matr=np.array([[1,2,3,4],
              [5,6,7,8]])
np.split(matr,2,axis=0)

[array([[1, 2, 3, 4]]), array([[5, 6, 7, 8]])]

In [29]:
ab=np.array([3,1,2,4])
np.sort(ab)

array([1, 2, 3, 4])

In [30]:
matt=np.array([[3,1,2],
               [6,5,4]])
print("sorted rows:\n",np.sort(matt,axis=1))

sorted rows:
 [[1 2 3]
 [4 5 6]]


In [31]:
print("sorted columns:\n",np.sort(matt,axis=0))

sorted columns:
 [[3 1 2]
 [6 5 4]]


In [3]:
import numpy as np


In [4]:
arr=np.array([[1,2],
              [3,4]])
arr1=np.array([[5,6],
              [3,4]])

In [5]:
np.concatenate((arr,arr1),axis=0)

array([[1, 2],
       [3, 4],
       [5, 6],
       [3, 4]])

In [6]:
np.concatenate((arr,arr1),axis=1)

array([[1, 2, 5, 6],
       [3, 4, 3, 4]])

In [7]:
#stacks arrays vertically(row_wise)
arr2=np.array([1,2,3])
arr3=np.array([4,5,6])
np.vstack((arr2, arr3))

array([[1, 2, 3],
       [4, 5, 6]])

In [8]:
a=np.array([1,2])
b=np.array([3,4])
np.hstack((a,b))

array([1, 2, 3, 4])

In [ ]:
#filtering

In [9]:
import numpy as np
aa=np.array([1,2,3,4,5,6])
mask=aa>3
filtered=aa[mask]
print("Filtered element >3:",filtered)

Filtered element >3: [4 5 6]


In [10]:
(aa>2)&(aa<6) #-------boolean

array([False, False,  True,  True,  True, False])

In [11]:
aa[(aa>2)&(aa<6)]    #------filtered

array([3, 4, 5])

In [12]:
aa[(aa<=3) | (aa>5)]

array([1, 2, 3, 6])

In [13]:
matrix=np.array([
    [10,15,20,],
    [25,30,35]
])
print("Values > 20:",matrix[matrix>20])

Values > 20: [25 30 35]


In [14]:
scores=np.array([85,92,78,88,95,72,89,94,68,90])
print("Scores values>90:",scores[scores>90])

Scores values>90: [92 95 94]


In [15]:
scores[(scores>70)  | (scores<80)]

array([85, 92, 78, 88, 95, 72, 89, 94, 68, 90])

In [16]:
import numpy as np
ab=np.arange(1,16)
ab

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [17]:
ab[ab%3==0]    #------numbers that rae divisible by 3

array([ 3,  6,  9, 12, 15])

In [18]:
ab[ab%3==0]    #------numbers that rae divisible by 3

array([ 3,  6,  9, 12, 15])

In [19]:
ab[ab%2!=0]    #-----odd numbers

array([ 1,  3,  5,  7,  9, 11, 13, 15])

In [20]:
ab[ab%2==0]    #----even numbers

array([ 2,  4,  6,  8, 10, 12, 14])

In [21]:
import numpy as np
temp=np.array([22.5,19.0,25.6,21.4,29.9,18.6,23.1,27.0])
temp[temp>24]

array([25.6, 29.9, 27. ])

In [22]:
temp[(temp > 20)  & (temp < 26)]

array([22.5, 25.6, 21.4, 23.1])

In [23]:
prices=np.array([250,499,520,310,800,999,450,720])
prices[prices>500]

array([520, 800, 999, 720])