In [ ]:
#creating nump0y array

In [1]:

import numpy as np
a= np.ones((3,4))
type(a)

numpy.ndarray

In [2]:
a

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [3]:
a1=np.zeros((2,4))
a1

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [4]:
zeros_array=np.zeros((3,3))
ones_array=np.ones((2,4))
zeros_array

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [5]:
ones_array

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [6]:
identity_matrix=np.eye(3)
identity_matrix

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [7]:
b=[1,2,3,4]
np.array(b,dtype=np.int32)

array([1, 2, 3, 4])

In [8]:
int_array=np.array([1,2,3], dtype=np.int32)
float_array=np.array([0.1,0.2,0.3],dtype=np.float64)
int_array

array([1, 2, 3])

In [9]:
float_array

array([0.1, 0.2, 0.3])

In [10]:
a2=np.arange(0,8)
a2

array([0, 1, 2, 3, 4, 5, 6, 7])

In [11]:
linspace_array=np.linspace(0,10,6)
linspace_array

array([ 0.,  2.,  4.,  6.,  8., 10.])

In [12]:
linspace_array1=np.linspace(0,20,5)
linspace_array1

array([ 0.,  5., 10., 15., 20.])

In [13]:
random_array=np.random.rand(4,4)
random_array

array([[0.8566368 , 0.34749196, 0.71723184, 0.77377866],
       [0.20185894, 0.43770632, 0.33641201, 0.04108622],
       [0.7888428 , 0.74626922, 0.10892331, 0.68584227],
       [0.1763358 , 0.84892025, 0.76609175, 0.43453974]])

In [ ]:
#basic indexing

In [14]:
arr=np.array([10,20,30,40])
print(arr[0])
print(arr[-1])

10
40


In [15]:
arr1=np.array([[23,4,6,3],[1,67,98,6]])
arr1

array([[23,  4,  6,  3],
       [ 1, 67, 98,  6]])

In [16]:
print(arr1[0,3])
print(arr1[1,-1])

3
6


In [ ]:
#1D array slicing

In [17]:
arr2=np.array([1,7,8,5,4,3])
print(arr2[1:4])
print(arr2[:6])
print(arr2[:-1])

[7 8 5]
[1 7 8 5 4 3]
[1 7 8 5 4]


In [18]:
matrix=np.array([[1,2,3],
                 [4,5,6],
                 [7,8,9]])
print(matrix[0:1,1:3])

[[2 3]]


In [19]:
print(matrix[2:3,1:2])
print(matrix[1:2,1:3])

[[8]]
[[5 6]]


In [20]:
v=np.array([1,2,3,4])
s=v[1:3]
s

array([2, 3])

In [21]:
#copy
a=np.array([1,2,3,4,5])
b=a[1:3].copy()
b

array([2, 3])

In [22]:
#shape
arr=np.array([[1,2,3],[4,5,6]])
arr.shape

(2, 3)

In [24]:
a=np.arange(12)
a


array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [25]:

b=a.reshape(3,4)
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [26]:
d=np.arange(20)
d

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [27]:
e=d.reshape(5,4)
e

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [28]:
arr_3d=np.array([[0,1,2],
              [4,5,6],
              [7,8,9]])
arr_3d.transpose()

array([[0, 4, 7],
       [1, 5, 8],
       [2, 6, 9]])

In [29]:
arr=np.array([[1,2,3,4,5,6],[10,20,30,40,50,60]])
arr.transpose()

array([[ 1, 10],
       [ 2, 20],
       [ 3, 30],
       [ 4, 40],
       [ 5, 50],
       [ 6, 60]])