In [1]:
#numpy
#array module
from array import array
my_array=('i',[2,5,7,8,6])
my_array 

('i', [2, 5, 7, 8, 6])

In [2]:
type(my_array)

tuple

In [ ]:
#numpy arrays

In [3]:
import numpy as np
arr=np.array([1,2,3,4,5])
arr

array([1, 2, 3, 4, 5])

In [4]:
type(arr)

numpy.ndarray

In [5]:
arr.ndim

1

In [6]:
arr.dtype

dtype('int32')

In [7]:
array_new = np.array([1,2,3,4,5])
array_new +3

array([4, 5, 6, 7, 8])

In [8]:
type(array_new)

numpy.ndarray

In [9]:
my_numpy_array=np.array([1,2,3,4,5])
new_array=my_numpy_array*3
new_array

array([ 3,  6,  9, 12, 15])

In [10]:
type(new_array)

numpy.ndarray

In [11]:
new_array>5

array([False,  True,  True,  True,  True])

In [12]:
matrix=np.array([
    [1,2,3],
    [4,3,5],
    [3,7,9]])
matrix

array([[1, 2, 3],
       [4, 3, 5],
       [3, 7, 9]])

In [13]:
arr_2d=np.array([[0,1,2],[3,4,5],[7,9,8]])
arr_2d*2

array([[ 0,  2,  4],
       [ 6,  8, 10],
       [14, 18, 16]])

In [14]:
type(arr_2d)

numpy.ndarray

In [15]:
arr_2d.ndim

2

In [16]:
arr_2d+2

array([[ 2,  3,  4],
       [ 5,  6,  7],
       [ 9, 11, 10]])

In [17]:
arr_2d-1

array([[-1,  0,  1],
       [ 2,  3,  4],
       [ 6,  8,  7]])

In [18]:
arr_2d%2

array([[0, 1, 0],
       [1, 0, 1],
       [1, 1, 0]], dtype=int32)

In [19]:
list_data = [1,6,5,7,9]
array_from_list=np.array(list_data)
list_data

[1, 6, 5, 7, 9]

In [20]:
type(list_data)

list

In [21]:
array_from_list

array([1, 6, 5, 7, 9])

In [22]:
type(array_from_list)

numpy.ndarray

In [23]:
array_from_list

array([1, 6, 5, 7, 9])